### ISSUE TITLE
Suggestion: splines2

### ISSUE THREAD

**Issue by wenjie2wang** [hwborchers/ctv-numericalmath#1]
Hi @hwborchers

I would like to suggest adding the [splines2](https://CRAN.R-project.org/package=splines2) package that I have been maintaining to Section "Interpolation and Approximation" of the task view.  Do you think it will be of interest?  I can create PR if you want.  Thanks.

**Comment by sgsokol** [comment]
Hi @wenjie2wang,

Thanks for submitting your package for this TaskView. Thematically, it is a very appropriate place to publish it. However, this repository is a private one. The official GitHub repository for this (and many other TaskViews) is under construction. So we (maintainers of the next version of TaskView "Numerical Mathematics") are asking you to be patient and wait until the release of the new TaskView.

Looking forward to your understanding and cooperation,
On behalf of the maintainer team,
Serguei Sokol.

**Comment by wenjie2wang** [comment]
@sgsokol thanks for your response.

**Comment by sgsokol** [comment]
Hi @wenjie2wang,

Now that a new version of TaskView infrastructure is online, may I suggest you to submit a patch request with your package description to https://github.com/cran-task-views/NumericalMathematics/ ?

Best,
Serguei Sokol.

**Comment by wenjie2wang** [comment]
Sure!  I will submit a PR.  Thanks for your suggestion.
